### ISSUE TITLE
Add docs to clayplatform.com

### ISSUE THREAD

**Issue by james-owen** [clay/claycli#146]
The claycli website / documentation should be added to docs.clayplatform.com

**Comment by oscarpolanco** [comment]
Hello @james-owen @PedroAlbR 
Sure we can add it.  The reason that `claycli` have his own page is that at the beginning of the docs task, I was told that every repo should have its own docs page. 

Can we add a ticket to discuss this issue?

**Comment by james-owen** [comment]
Hi @oscarpolanco where are the claycli docs currently?

**Comment by oscarpolanco** [comment]
At this url => https://docs.clayplatform.com/claycli/docs/cli.html
@james-owen

**Comment by james-owen** [comment]
In this case, they're already on docs.clayplatform.com, but we could just add a link to the docs. If I go to the main page, there's no obvious way to get to the claycli docs.

**Comment by oscarpolanco** [comment]
Agreed; we can put it on the [Getting Started](https://docs.clayplatform.com/docs/getting-started) page or  on the [Glossary](https://docs.clayplatform.com/docs/glossary)
What do you think?

**Comment by james-owen** [comment]
Definitely in the Glossary, but there should also be something on the front page--either a section that describes how Clay is built of many parts with links to the docs, or a link to another "clay overview" page. Would also be interested in what @TTaitFoster thinks.

**Comment by TTaitFoster** [comment]
Sorry for the delay guys!

All of this sounds right. I think it makes sense to have a Glossary @oscarpolanco and I agree with @james-owen that a "Clay Overview" would be a good idea.

**Comment by oscarpolanco** [comment]
Thanks for your time @james-owen @TTaitFoster 😄 
I'm gonna close this issue and create a ticket for the new task

**Comment by oscarpolanco** [comment]
Here the tickets
 - https://app.zenhub.com/workspaces/clay-repos-596524da4a8a0769f2f03175/issues/clay/clay.github.io/9

- https://app.zenhub.com/workspaces/clay-repos-596524da4a8a0769f2f03175/issues/clay/clay.github.io/10
Feel free to edit the tickets 😅 
@james-owen @TTaitFoster
