### ISSUE TITLE
Feature Request: Debug url

### ISSUE THREAD

**Issue by byronhulcher** [clay/claycli#20]
I would like the ability to pass a url (for instance: http://nymag.com/selectall/2017/04/the-secrets-of-the-times-square-olive-garden-revealed.html) to `clay-cli` and discover possible reasons why the url might be returning a 404 or 500.  Ideally this would:

1) Check that there is an existing `uri` for the published page
2) If so, check that the page has a published version
3) lint the layout of the page
4) lint all non-layout components on the page

and if any of these failed, it would display an error message explaining the problem.  This would greatly assist in debugging imported pages, as QA and Product usually pass a broken page to dev by its url and checking all of these things can be a manual process.

**Comment by nelsonpecora** [comment]
page uri added in commit 2a01f1c

**Comment by nelsonpecora** [comment]
added in v0.3.0!
