### ISSUE TITLE
idea: programmatic api

### ISSUE THREAD

**Issue by nelsonpecora** [clay/claycli#30]
* we should allow all of the `claycli` methods to be used programmatically
* individual commands should be importable, lodash-style (e.g. `require('claycli/import')`)
* full api should be importable, lodash-style (e.g. `require('claycli').import`)
* programmatic `claycli` should still use streams (and use all of the logic in `io/`) under the hood, but maybe should expose a promise-based api?

**Comment by jonwinton** [comment]
Eh, Highland gives you a `toPromise` method and streams are more efficient for a lot of what we're doing. I'd say full streams and if it's an issue just pull Highland into your project, wrap it and use `toPromise`

**Comment by nelsonpecora** [comment]
Yeah, that kinda makes more sense
