### ISSUE TITLE
replace current logger with clay-log

### ISSUE THREAD

**Issue by amycheng** [clay/claycli#38]
use [Clay-log](https://github.com/clay/clay-log) instead of the logger that is being used now.

we might as well be consistent with the other clay things. 

see [here](https://github.com/clay/clay-kiln/blob/master/lib/page-data/actions.js#L30) for usage

**Comment by nelsonpecora** [comment]
Note: we'll also want to standardize what the output looks like (e.g. what happens on errors, what do successes look like) since we're making heavy use of stdin / stdout

**Comment by nelsonpecora** [comment]
Actually, it looks like we can't use `clay-log`, since that hardcodes its output to `stdout`

**Comment by nelsonpecora** [comment]
should work with https://github.com/clay/clay-log/pull/5
