### ISSUE TITLE
Script Compilation

### ISSUE THREAD

**Issue by nelsonpecora** [clay/claycli#44]
* move megabundler to claycli
* allow megabundler to work with client.js
* determine script compilation api (watch, minify, etc)

Since this is the first compilation aspect that we're bringing into claycli:

* determine how compilation should be scaffolded (streams? gulp? etc)
* write helper functions to deal with incremental compilation, file watching, etc

**Comment by amycheng** [comment]
would it be too crazy to ask for live reloading???

**Comment by nelsonpecora** [comment]
Yes. Probably. Maybe. Live reload is suuuuuper buggy in literally every implementation I've seen of it, and I don't really know why. ¯\_(ツ)_/¯

**Comment by nelsonpecora** [comment]
# Current

* component js
  * copy kiln files
  * build kiln plugins
  * build model.js
  * build client.js
* component templates (recompilation)
* view before (comscore, fb, gs)
* view after (init component controllers + DS)

# Requirements

* `components/:name/model.js` → `public/js/models.js`
* `components/:name/client.js` → `public/js/:name.client.js`
* `services/**/*.js` → `public/js/:name.service.js`
* dependencies → `:number.js` (inlined for readers) + `deps-:number.js` (linked for kiln)
* needs a programmatic api to figure out the stuff for resolve-media
* cache to `browserify-cache.json`
* megabundler features:
	* bundles globs:
		* `components/*/model.js`
		* `components/*/client.js`
		* `global/js/*.js` (!!)
		* `global/kiln-js/index.js` (!!!)
		* ignore `*.test.js`
		* ignore `global/js/components.js` (?!)
	* delete existing `public/js/deps-*.js`, `public/js/models.js`
	* if `--compact`, uses browserify cache
	* `babelify`
		* `es2015`
		* `transform-es2015-modules-commonjs`
	* `vueify`
		* `es2015`
		* `transform-es2015-modules-commonjs`
	* extract css → `public/css/edit-before.css` (change this)
	* TODO: figure out why we're replacing `jsdom` → `window`
	* replace `services/server/*.js` → `services/client/*.js`
	* assign modules IDs
	* filter unchanged files (via cache, for incremental)
	* extract browserify registry
	* extract module IDs
	* browserify global pack
	* replace `process.env` → `window.process.env`
	* if `--compact` call `uglifyify`, collapse bundle
	* merge subcache into cache
	* registry cache → `public/js/registry.json`
	* env cache → `client-env.json`
	* id cache → `public/js/ids.json`
	* if `--watch` start watching cached files + entry globs

**Comment by nelsonpecora** [comment]
# Updated Requirements

#### files

* `components/:name/client.js` → `public/js/:name.client.js`
	* deps → `public/js/:number.js`
	* deps, for linking in the future → `public/js/_client-deps-:letter-:letter.js`
		* `_client-deps-a-d.js`
		* `_client-deps-e-h.js`
		* `_client-deps-i-l.js`
		* `_client-deps-m-p.js`
		* `_client-deps-q-t.js`
		* `_client-deps-u-z.js`
* `components/:name/model.js` → `public/js/:name.model.js`
	* → `public/js/_models-:letter-:letter.js`
	* consolidated models, for kiln
		* `_models-a-d.js`
		* `_models-e-h.js`
		* `_models-i-l.js`
		* `_models-m-p.js`
		* `_models-q-t.js`
		* `_models-u-z.js`
	* deps, for kiln → `public/js/_model-deps-:letter-:letter.js`
		* `_model-deps-a-d.js`
		* `_model-deps-e-h.js`
		* `_model-deps-i-l.js`
		* `_model-deps-m-p.js`
		* `_model-deps-q-t.js`
		* `_model-deps-u-z.js`
* dependencies share same ID for client and model
	* → `public/js/_ids.json`
	* → `public/js/_registry.json`
	* → `client-env.json` (gitignored)
	* → `browserify-cache.json` (gitignored)
* `services/kiln` used for all kiln plugins
	* consolidated js → `public/js/_kiln-plugins.js`
	* consolidated css → `public/css/_kiln-plugins.css`
* glob (or array of globs) passthrough for legacy global scripts
	* js → `public/js/_global.js`
* claycli automatically generates client component controller initialization script → `public/js/_client-init.js`
* copy kiln scripts (if they exist)
	* `node_modules/clay-kiln/dist/clay-kiln-edit.js` → `public/js/clay-kiln-edit.js`
	* `node_modules/clay-kiln/dist/clay-kiln-view.js` → `public/js/clay-kiln-view.js`

#### rules

* needs a programmatic api to figure out the stuff for `resolveMedia`
* cache to `browserify-cache.json`
* ignore `*.test.js`
* if `minify`, use browserify cache
* `babelify`
	* `es2015`
	* `transform-es2015-modules-commonjs`
* `vueify`
	* `es2015`
	* `transform-es2015-modules-commonjs`
* extract kiln plugin css
* TODO: figure out why we're replacing `jsdom` with `window`
* replace `services/server/*.js` with `services/client/*.js`
	* TODO: this might be deprecated, because `services/universal/*.js` does it automatically
* assign module IDs
* filter unchanged files (via cache, for incremental builds)
* extract browserify registry
* extract module IDs
* browserify global pack
* replace `process.env` with `window.process.env`
* if `minify`, call `uglifyify` and collapse bundle
* merge subcache into cache
* registry cache → `public/js/_registry.json`
* env cache → `client-env.json`
* id cache → `public/js/_ids.json`
* if `watch` start watching cached files + entry globs

**Comment by nelsonpecora** [comment]
I'm not sure if splitting the `client.js` and `model.js` dependencies will lead to significant filesize reduction for kiln, but I'm pursuing it and testing it against the filesizes of the combined (current gulp) dependencies. If it ends up not being worth the increased compilation complexity, I'll switch it back to bundling all the deps together.

**Comment by nelsonpecora** [comment]
Splitting them out did _not_ meaningfully decrease the dependency size, so we're consolidating them again. Here are the new specs:

#### files

* `components/:name/client.js` → `public/js/:name.client.js`
	* deps → `public/js/:number.js`
* `components/:name/model.js` → `public/js/:name.model.js`
	* → `public/js/_models-:letter-:letter.js`
	* consolidated models, for kiln
		* `_models-a-d.js`
		* `_models-e-h.js`
		* `_models-i-l.js`
		* `_models-m-p.js`
		* `_models-q-t.js`
		* `_models-u-z.js`
	* deps (combined models + clients), for kiln → `public/js/_deps-:letter-:letter.js`
		* `_deps-a-d.js`
		* `_deps-e-h.js`
		* `_deps-i-l.js`
		* `_deps-m-p.js`
		* `_deps-q-t.js`
		* `_deps-u-z.js`
* dependencies have some files they write out:
	* → `public/js/_prelude.js`
	* → `public/js/_postlude.js`
	* → `public/js/_ids.json`
	* → `public/js/_registry.json`
	* → `client-env.json` (gitignored)
	* → `browserify-cache.json` (gitignored)
* `services/kiln` used for all kiln plugins
	* consolidated js → `public/js/_kiln-plugins.js`
	* consolidated css → `public/css/_kiln-plugins.css`
* glob (or array of globs) passthrough for legacy global scripts
	* js → `public/js/_global.js`
* claycli automatically generates client component controller initialization script → `public/js/_client-init.js`
* copy kiln scripts (if they exist)
	* `node_modules/clay-kiln/dist/clay-kiln-edit.js` → `public/js/clay-kiln-edit.js`
	* `node_modules/clay-kiln/dist/clay-kiln-view.js` → `public/js/clay-kiln-view.js`

#### rules

* needs a programmatic api to figure out the stuff for `resolveMedia`
* cache to `browserify-cache.json`
* if `!minify`, use browserify cache
* `babelify`
	* `es2015`
	* `transform-es2015-modules-commonjs`
* `vueify`
	* `es2015`
	* `transform-es2015-modules-commonjs`
* extract kiln plugin css
* alias out `jsdom` everywhere
* replace `services/server/*.js` with `services/client/*.js`
* assign module IDs
* filter unchanged files (via cache, for incremental builds)
* extract browserify registry
* extract module IDs
* browserify global pack
* replace `process.env` with `window.process.env`
* if `minify`, call `uglifyify` and collapse bundle
* merge subcache into cache
* registry cache → `public/js/_registry.json`
* env cache → `client-env.json`
* id cache → `public/js/_ids.json`
* if `watch` start watching cached files + entry globs

**Comment by nelsonpecora** [comment]
# Notes

* `COMPACT_BUILD` is now `CLAYCLI_COMPILE_MINIFIED` (which works on scripts, styles, fonts, and templates)
* new env variable: `CLAYCLI_COMPILE_MINIFIED_SCRIPTS`
* file sizes:
	* combined (legacy gulp) dependencies was 5.26MB in 10 files
	* combined (legacy gulp) models was 388KB in 1 file
	* new models is 400KB in 6 files
	* new dependencies is 4.44MB in 6 files
	* old: 1017 deps, new: 800 deps
* make sure you `.gitignore` these:
	* `client-env.json` - list of env variables for models
	* `browserify-cache.json` - for incremental builds
* move `global/kiln-js` to `services/kiln`
	* kiln should filter `window.modules` for model.js files and mount them on `window.kiln.componentModels` (removes edit-after.js)
	* `services/kiln/index.js` is the entry point for kiln plugins, validators, etc and must `require()` them
	* kiln plugins share the same deduped dependencies as models (and client.js)
* watching:
	* `client.js`, `model.js`, `services/kiln/index.js`, legacy `_global.js` globs, and their deps
	* kiln scripts (to copy over)

# Migration Steps

* move kiln plugins to `services/kiln`
* add script globbing for legacy js
