### ISSUE TITLE
CLI - Page URL

### ISSUE THREAD

**Issue by pfeytser** [clay/claycli#48]
People have URL prop in page data, will convert to custom URL.

**Comment by nelsonpecora** [comment]
The fix for this is:

* non-versioned pages with `url` should save it as `customUrl`
* `claycli` should print a warning about this

**Comment by nelsonpecora** [comment]
fixed by https://github.com/clay/claycli/pull/50

**Comment by nelsonpecora** [comment]
Note: claycli will warn about this in the _next_ major version
