### ISSUE TITLE
figure out automatic css cleaning and linter rules

### ISSUE THREAD

**Issue by nelsonpecora** [clay/claycli#65]
We need to, in parallel:

* develop scripts that will automatically clean up our css when we switch over to styleguides
* write linter rules that the auto-cleaner will pass
* enable or disable postcss features based on what the auto-cleaner can do (require nesting if it can auto-nest, disable nesting otherwise and lint for it otherwise, for example)
* try to match parity with per-instance styles

**Comment by amycheng** [comment]
https://github.com/nymag/sites/blob/css-next/scripts/css-next/clean-css.js

**Comment by nelsonpecora** [comment]
figured it out! on the `sites/css-next` branch
