### ISSUE TITLE
Lint, but for rendered version

### ISSUE THREAD

**Issue by jonwinton** [clay/claycli#70]
We've run into a couple issues where all components exist but the data that's associated with the component is incongruous with the template for rendering. It would be nice to be able to lint by extension to identify which component is broken when a page is complete from a JSON perspective.

**Comment by reubenson** [comment]
Agreed, if all references exist but the page still 404s, the only recourse is to manually test the html endpoint for each component on the page. something like an `--html` flag on clay lint would be very useful for speeding up the page debugging process

**Comment by nelsonpecora** [comment]
Hmm, I think I know how to implement this
