### ISSUE TITLE
Programmatic `export.fromURL` stream returns Objects while programmatic `import` expects Strings

### ISSUE THREAD

**Issue by byronhulcher** [clay/claycli#81]
The resultant dispatches from a claycli.exportFromUrl are all native Javascript objects. However, the `import` function will throw an error if I attempt to pass them on directly. Instead, I am required to `JSON.stringify()` them. This seems counter-intuitive.

**Comment by nelsonpecora** [comment]
Feature: allow streaming in objects directly on `import`
